### ISSUE TITLE
Can you make divided seek bar? Please support if you can . Thanks.

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [emadabdalrahman/MusicBar#1]
How to make divided wave seek bar? or want to update like this.
![screenshot_20181215-111830__01](https://user-images.githubusercontent.com/19220742/50039180-db226880-005b-11e9-8655-db6894dbec50.jpg)
![screenshot_20181215-111653__01__01](https://user-images.githubusercontent.com/19220742/50039181-dbbaff00-005b-11e9-9110-5d1333a5f6a9.jpg)

**Comment by emadabdalrahman** [comment]
the divided bar will be in the upcoming update.

**Comment by Thet-Tun-Aung** [comment]
> 
> 
> the divided bar will be in the upcoming update.

Thanks , waiting ....

**Comment by Thet-Tun-Aung** [comment]
Thanks so much @emadabdalrahman  . Please give me access for pull request.  👍
