### ISSUE TITLE
Requesting smooth scrollable bar.

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [emadabdalrahman/MusicBar#2]
Dear @emadabdalrahman , Please make auto seek bar to a smooth behavior like below:Thanks so much.

![20190105_172329611](https://user-images.githubusercontent.com/19220742/50723666-0f46f180-110f-11e9-9451-4652adab88d7.gif)

**Comment by emadabdalrahman** [comment]
ok I will add that in next update

**Comment by Thet-Tun-Aung** [comment]
> 
> 
> ok I will add that in next update

Thank you so much @emadabdalrahman
