### ISSUE TITLE
Anyway to load from remote server ?

### ISSUE THREAD

**Issue by dariush-fathie** [emadabdalrahman/MusicBar#3]
this library is really awesome . 
but can we load from remote server ?

thank you .

**Comment by emadabdalrahman** [comment]
the library needs to read media file to calculate the right height for each bar in the view but with stream music, you will just receive a stream of data that represent a number of seconds so it is difficult to calculate the right height for each bar.
but if we can make part of the calculation in the server then view take that information to calculate the height then draw view.
